packages:
  - apps/*
  - packages/*

catalog:
  '@base-ui/react': ^1.1.0
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@eslint-community/eslint-plugin-eslint-comments': ^4.6.0
  '@eslint/js': ^9.39.2
  '@fontsource-variable/inter': ^5.2.8
  '@fontsource-variable/jetbrains-mono': ^5.2.8
  '@ianvs/prettier-plugin-sort-imports': ^4.7.1
  '@lexical/react': ^0.39.0
  '@lexical/utils': ^0.39.0
  '@storybook/addon-a11y': ^10.2.7
  '@storybook/addon-docs': ^10.2.7
  '@storybook/addon-themes': ^10.2.7
  '@storybook/react-vite': ^10.2.7
  '@tailwindcss/cli': ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  '@types/node': ^24.10.11
  '@types/react': ^19.2.13
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/utils': ^8.53.0
  '@vitejs/plugin-react': ^5.1.3
  cva: 1.0.0-beta.4
  del-cli: ^7.0.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-depend: ^1.4.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-n: ^17.23.2
  eslint-plugin-react-dom: ^2.6.4
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-hooks-extra: ^2.6.4
  eslint-plugin-react-naming-convention: ^2.6.4
  eslint-plugin-react-refresh: ^0.4.26
  eslint-plugin-react-web-api: ^2.6.4
  eslint-plugin-react-x: ^2.6.4
  eslint-plugin-storybook: ^10.2.7
  eslint-plugin-unicorn: ^62.0.0
  globals: ^17.0.0
  lexical: ^0.39.0
  lucide-react: ^0.563.0
  prettier: ^3.8.1
  prettier-plugin-tailwindcss: ^0.7.2
  react: ^19.2.4
  react-dom: ^19.2.4
  sherif: ^1.10.0
  storybook: ^10.2.7
  tailwindcss: ^4.1.18
  turbo: ^2.8.3
  typescript: ^5.9.3
  typescript-eslint: ^8.53.0
  vite: ^7.3.1

catalogMode: strict

cleanupUnusedCatalogs: true

engineStrict: true

nodeOptions: '--experimental-strip-types'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

publicHoistPattern:
  - '*storybook*'
