packages:
  - apps/*
  - packages/*

catalog:
  '@base-ui/react': ^1.1.0
  '@changesets/changelog-github': ^0.6.0
  '@changesets/cli': ^2.30.0
  '@eslint-community/eslint-plugin-eslint-comments': ^4.7.1
  '@eslint/js': ^10.0.1
  '@fontsource-variable/inter': ^5.2.8
  '@fontsource-variable/jetbrains-mono': ^5.2.8
  '@storybook/addon-a11y': ^10.3.5
  '@storybook/addon-docs': ^10.3.5
  '@storybook/addon-themes': ^10.3.5
  '@storybook/react-vite': ^10.3.5
  '@tailwindcss/cli': ^4.1.18
  '@tailwindcss/vite': ^4.2.2
  '@types/node': ^24.12.2
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^6.0.1
  cva: 1.0.0-beta.4
  del-cli: ^7.0.0
  eslint: ^10.2.0
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-compat: ^7.0.1
  eslint-plugin-depend: ^1.5.0
  eslint-plugin-import-x: ^4.16.2
  eslint-plugin-n: ^17.24.0
  eslint-plugin-react-dom: ^4.2.3
  eslint-plugin-react-jsx: ^4.2.3
  eslint-plugin-react-naming-convention: ^4.2.3
  eslint-plugin-react-refresh: ^0.5.2
  eslint-plugin-react-rsc: ^4.2.3
  eslint-plugin-react-web-api: ^4.2.3
  eslint-plugin-react-x: ^4.2.3
  eslint-plugin-storybook: ^10.3.5
  eslint-plugin-unicorn: ^64.0.0
  globals: ^17.5.0
  lucide-react: ^0.563.0
  oxfmt: ^0.45.0
  react: ^19.2.4
  react-dom: ^19.2.4
  sherif: ^1.11.1
  storybook: ^10.3.5
  tailwindcss: ^4.2.2
  turbo: ^2.9.14
  typescript: ^5.9.3
  typescript-eslint: ^8.58.2
  vite: ^8.0.8

catalogMode: strict

cleanupUnusedCatalogs: true

engineStrict: true

nodeOptions: '--experimental-strip-types'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

publicHoistPattern:
  - '*storybook*'
