nodeOptions: '--experimental-strip-types'
packages:
  - 'tooling/*'
catalog:
  '@types/node': ^22.15.31
  'eslint': ^9.29.0
  'prettier': ^3.5.3
  'tsup': ^8.5.0
  'typescript': ^5.8.3
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
