packages:
  - apps/*
  - packages/*

catalog:
  '@changesets/cli': ^2.29.5
  '@eslint/js': ^9.31.0
  '@fontsource-variable/inter': ^5.2.6
  '@fontsource-variable/jetbrains-mono': ^5.2.6
  '@storybook/addon-a11y': ^9.0.17
  '@storybook/addon-docs': ^9.0.17
  '@storybook/addon-themes': ^9.0.17
  '@storybook/react-vite': ^9.0.17
  '@tailwindcss/cli': ^4.1.11
  '@tailwindcss/vite': ^4.1.11
  '@types/node': ^22.15.31
  '@types/react-dom': ^19.1.6
  '@types/react': ^19.1.8
  '@vitejs/plugin-react': ^4.5.2
  cva: 1.0.0-beta.4
  del-cli: ^6.0.0
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-n: ^17.21.0
  eslint-plugin-storybook: ^9.0.17
  eslint: ^9.31.0
  globals: ^16.3.0
  prettier-plugin-tailwindcss: ^0.6.13
  prettier: ^3.6.2
  react-dom: ^19.1.0
  react: ^19.1.0
  sherif: ^1.6.1
  storybook: ^9.0.17
  tailwindcss: ^4.1.11
  tsup: ^8.5.0
  typescript-eslint: ^8.37.0
  typescript: ^5.8.3
  vite: ^6.3.5
  eslint-plugin-react-dom: ^1.52.3
  eslint-plugin-react-hooks-extra: ^1.52.3
  eslint-plugin-react-naming-convention: ^1.52.3
  eslint-plugin-react-web-api: ^1.52.3
  eslint-plugin-react-x: ^1.52.3

catalogMode: strict

engineStrict: true

nodeOptions: '--experimental-strip-types'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

publicHoistPattern:
  - '*storybook*'
