packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tailwindcss/vite': 4.1.10
  '@types/node': 22.15.31
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  '@vitejs/plugin-react': 4.5.2
  eslint: 9.29.0
  prettier: 3.5.3
  react: 19.1.0
  react-dom: 19.1.0
  tailwindcss: 4.1.10
  tsup: 8.5.0
  typescript: 5.8.3
  vite: 6.3.5

engineStrict: true

nodeOptions: '--experimental-strip-types'

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
