packages:
  - apps/*
  - packages/*

catalog:
  '@changesets/cli': ^2.29.6
  '@eslint/js': ^9.34.0
  '@fontsource-variable/inter': ^5.2.6
  '@fontsource-variable/jetbrains-mono': ^5.2.6
  '@ianvs/prettier-plugin-sort-imports': ^4.6.3
  '@lexical/react': ^0.34.0
  '@lexical/utils': 0.34.0
  '@storybook/addon-a11y': ^9.1.3
  '@storybook/addon-docs': ^9.1.3
  '@storybook/addon-themes': ^9.1.3
  '@storybook/react-vite': 9.1.3
  '@tailwindcss/cli': ^4.1.12
  '@tailwindcss/vite': ^4.1.12
  '@types/node': ^22.15.31
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react': ^4.5.2
  cva: 1.0.0-beta.4
  del-cli: ^6.0.0
  eslint: ^9.34.0
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-n: ^17.21.3
  eslint-plugin-react-dom: ^1.52.6
  eslint-plugin-react-hooks-extra: ^1.52.6
  eslint-plugin-react-naming-convention: ^1.52.6
  eslint-plugin-react-web-api: ^1.52.6
  eslint-plugin-react-x: ^1.52.6
  eslint-plugin-storybook: ^9.1.3
  eslint-plugin-unicorn: ^60.0.0
  globals: ^16.3.0
  lexical: ^0.34.0
  lucide-react: ^0.541.0
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.1.0
  react-dom: ^19.1.0
  sherif: ^1.6.1
  storybook: ^9.1.3
  tailwindcss: ^4.1.12
  turbo: ^2.5.6
  typescript: ^5.9.2
  typescript-eslint: ^8.41.0
  vite: ^6.3.5

catalogMode: strict

cleanupUnusedCatalogs: true

engineStrict: true

nodeOptions: '--experimental-strip-types'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

publicHoistPattern:
  - '*storybook*'
