packages:
  - apps/*
  - packages/*

catalog:
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@eslint/js': ^9.39.1
  '@fontsource-variable/inter': ^5.2.8
  '@fontsource-variable/jetbrains-mono': ^5.2.8
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@lexical/react': ^0.37.0
  '@lexical/utils': ^0.37.0
  '@storybook/addon-a11y': ^10.0.3
  '@storybook/addon-docs': ^10.0.3
  '@storybook/addon-themes': ^10.0.3
  '@storybook/react-vite': ^10.0.3
  '@tailwindcss/cli': ^4.1.16
  '@tailwindcss/vite': ^4.1.16
  '@types/node': ^24.10.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@typescript-eslint/utils': ^8.46.3
  '@vitejs/plugin-react': ^5.1.0
  cva: 1.0.0-beta.4
  del-cli: ^7.0.0
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-depend: ^1.3.1
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-n: ^17.23.1
  eslint-plugin-react-dom: ^2.3.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-hooks-extra: ^2.3.1
  eslint-plugin-react-naming-convention: ^2.3.1
  eslint-plugin-react-refresh: ^0.4.24
  eslint-plugin-react-web-api: ^2.3.1
  eslint-plugin-react-x: ^2.3.1
  eslint-plugin-storybook: ^10.0.3
  eslint-plugin-unicorn: ^62.0.0
  globals: ^16.5.0
  lexical: ^0.37.0
  lucide-react: ^0.552.0
  prettier: ^3.8.0
  prettier-plugin-tailwindcss: ^0.7.2
  react: ^19.2.0
  react-dom: ^19.2.0
  sherif: ^1.9.0
  storybook: ^10.0.3
  tailwindcss: ^4.1.16
  turbo: ^2.7.4
  typescript: ^5.9.3
  typescript-eslint: ^8.46.3
  vite: ^7.1.12

catalogMode: strict

cleanupUnusedCatalogs: true

engineStrict: true

nodeOptions: '--experimental-strip-types'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

publicHoistPattern:
  - '*storybook*'
