packages:
  - apps/*
  - packages/*

catalog:
  '@fontsource-variable/inter': ^5.2.6
  '@fontsource-variable/jetbrains-mono': ^5.2.6
  '@tailwindcss/cli': ^4.1.11
  '@tailwindcss/vite': ^4.1.11
  '@types/node': ^22.15.31
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react': ^4.5.2
  cva: 1.0.0-beta.4
  del-cli: ^6.0.0
  eslint: ^9.29.0
  prettier: ^3.5.3
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: ^4.1.11
  tsup: ^8.5.0
  typescript: ^5.8.3
  vite: ^6.3.5
  '@storybook/addon-themes': ^9.0.14
  '@storybook/addon-a11y': ^9.0.14
  '@storybook/addon-docs': ^9.0.14
  '@storybook/react-vite': ^9.0.14
  storybook: ^9.0.14

catalogMode: strict

engineStrict: true

nodeOptions: '--experimental-strip-types'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

publicHoistPattern:
  - '*storybook*'
