import confusingBrowserGlobals from 'confusing-browser-globals';
import type { DummyRuleMap } from 'oxlint';

export const eslintRules = {
  'accessor-pairs': 'error',
  'array-callback-return': ['error', { allowImplicit: true }],
  'arrow-body-style': 'error',
  'block-scoped-var': 'error',
  'capitalized-comments': 'off',
  'class-methods-use-this': 'off',
  'complexity': 'off',
  'constructor-super': 'error',
  'curly': 'error',
  'default-case-last': 'error',
  'default-case': 'off',
  'default-param-last': 'error',
  'eqeqeq': 'error',
  'for-direction': 'error',
  'func-name-matching': 'off',
  'func-names': 'off',
  'func-style': ['error', 'declaration'],
  'getter-return': 'error',
  'grouped-accessor-pairs': ['error', 'getBeforeSet'],
  'guard-for-in': 'error',
  'id-denylist': 'off',
  'id-length': 'off',
  'id-match': 'off',
  'init-declarations': 'off',
  'logical-assignment-operators': 'off',
  'max-classes-per-file': 'off',
  'max-depth': 'off',
  'max-lines-per-function': 'off',
  'max-lines': 'off',
  'max-nested-callbacks': 'off',
  'max-params': 'off',
  'max-statements': 'off',
  'new-cap': 'error',
  'no-alert': 'error',
  'no-array-constructor': 'error',
  'no-async-promise-executor': 'error',
  'no-await-in-loop': 'error',
  'no-bitwise': 'error',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': ['error', 'always'],
  'no-console': 'error',
  'no-const-assign': 'error',
  'no-constant-binary-expression': 'error',
  'no-constant-condition': 'error',
  'no-constructor-return': 'error',
  'no-continue': 'error',
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-div-regex': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-else-if': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-duplicate-imports': 'off',
  'no-else-return': ['error', { allowElseIf: false }],
  'no-empty-character-class': 'error',
  'no-empty-function': 'error',
  'no-empty-pattern': 'error',
  'no-empty-static-block': 'error',
  'no-empty': ['error', { allowEmptyCatch: true }],
  'no-eq-null': 'off',
  'no-eval': 'error',
  'no-ex-assign': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-boolean-cast': ['error', { enforceForInnerExpressions: true }],
  'no-extra-label': 'off',
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-implicit-coercion': 'error',
  'no-implicit-globals': 'error',
  'no-implied-eval': 'off',
  'no-import-assign': 'error',
  'no-inline-comments': 'off',
  'no-inner-declarations': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-iterator': 'error',
  'no-label-var': 'off',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-loop-func': 'error',
  'no-loss-of-precision': 'error',
  'no-magic-numbers': 'off',
  'no-misleading-character-class': 'error',
  'no-multi-assign': 'error',
  'no-multi-str': 'error',
  'no-negated-condition': 'off',
  'no-nested-ternary': 'off',
  'no-new-func': 'error',
  'no-new-native-nonconstructor': 'error',
  'no-new-wrappers': 'error',
  'no-new': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-obj-calls': 'error',
  'no-object-constructor': 'error',
  'no-param-reassign': 'error',
  'no-plusplus': 'off',
  'no-promise-executor-return': 'error',
  'no-proto': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'error',
  'no-restricted-exports': 'off',
  'no-restricted-globals': [
    'error',
    {
      name: 'Buffer',
      message: 'Use Uint8Array instead. See: https://sindresorhus.com/blog/goodbye-nodejs-buffer',
    },
    {
      name: 'atob',
      message:
        'This API is deprecated. Use https://github.com/sindresorhus/uint8array-extras instead.',
    },
    {
      name: 'btoa',
      message:
        'This API is deprecated. Use https://github.com/sindresorhus/uint8array-extras instead.',
    },
    ...confusingBrowserGlobals,
  ],
  'no-restricted-imports': 'off',
  'no-restricted-properties': 'off',
  'no-return-assign': ['error', 'always'],
  'no-script-url': 'error',
  'no-self-assign': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-setter-return': 'error',
  'no-shadow-restricted-names': 'error',
  'no-shadow': 'error',
  'no-sparse-arrays': 'error',
  'no-template-curly-in-string': 'error',
  'no-ternary': 'off',
  'no-this-before-super': 'error',
  'no-throw-literal': 'off',
  'no-unassigned-vars': 'error',
  'no-undef': 'error',
  'no-undefined': 'off',
  'no-underscore-dangle': 'off',
  'no-unexpected-multiline': 'off',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': 'error',
  'no-unreachable-loop': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': ['error', { enforceForOrderingRelations: true }],
  'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
  'no-unused-expressions': ['error', { enforceForJSX: true }],
  'no-unused-labels': 'off',
  'no-unused-private-class-members': 'error',
  'no-unused-vars': ['error', { ignoreRestSiblings: true }],
  'no-use-before-define': 'off',
  'no-useless-assignment': 'error',
  'no-useless-backreference': 'error',
  'no-useless-call': 'error',
  'no-useless-catch': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-escape': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-void': 'error',
  'no-warning-comments': 'off',
  'no-with': 'error',
  'object-shorthand': [
    'error',
    'always',
    {
      avoidExplicitReturnArrows: true,
      avoidQuotes: true,
    },
  ],
  'one-var': ['error', 'never'],
  'operator-assignment': 'off',
  'prefer-arrow-callback': ['error', { allowNamedFunctions: true }],
  'prefer-const': ['error', { destructuring: 'all' }],
  'prefer-destructuring': [
    'error',
    {
      VariableDeclarator: {
        array: false,
        object: true,
      },
      AssignmentExpression: {
        array: false,
        object: false,
      },
    },
    { enforceForRenamedProperties: false },
  ],
  'prefer-exponentiation-operator': 'error',
  'prefer-named-capture-group': 'off',
  'prefer-numeric-literals': 'error',
  'prefer-object-has-own': 'error',
  'prefer-object-spread': 'error',
  'prefer-promise-reject-errors': 'off',
  'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'off',
  'preserve-caught-error': 'error',
  'radix': 'error',
  'require-await': 'off',
  'require-unicode-regexp': 'error',
  'require-yield': 'error',
  'sort-imports': 'off',
  'sort-keys': 'off',
  'sort-vars': 'off',
  'symbol-description': 'error',
  'unicode-bom': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'error',
  'vars-on-top': 'off',
  'yoda': 'error',
} as const satisfies DummyRuleMap;
