import type { DummyRuleMap } from 'oxlint';

export const importRules = {
  'import/consistent-type-specifier-style': ['error', 'prefer-top-level-if-only-type-imports'],
  'import/default': 'off',
  'import/export': 'off',
  'import/exports-last': 'off',
  'import/extensions': ['error', 'ignorePackages'],
  'import/first': 'error',
  'import/group-exports': 'off',
  'import/max-dependencies': 'off',
  'import/named': 'off',
  'import/namespace': 'off',
  'import/newline-after-import': 'off',
  'import/no-absolute-path': 'error',
  'import/no-amd': 'error',
  'import/no-anonymous-default-export': 'off',
  'import/no-commonjs': 'off',
  'import/no-cycle': 'error',
  'import/no-default-export': 'off',
  'import/no-duplicates': ['error', { preferInline: true }],
  'import/no-dynamic-require': 'off',
  'import/no-empty-named-blocks': 'off',
  'import/no-mutable-exports': 'error',
  'import/no-named-as-default-member': 'error',
  'import/no-named-as-default': 'error',
  'import/no-named-default': 'error',
  'import/no-named-export': 'off',
  'import/no-namespace': 'off',
  'import/no-nodejs-modules': 'off',
  'import/no-relative-parent-imports': 'off',
  'import/no-self-import': 'error',
  'import/no-unassigned-import': 'off',
  'import/no-webpack-loader-syntax': 'error',
  'import/prefer-default-export': 'off',
  'import/unambiguous': 'off',
} as const satisfies DummyRuleMap;
