import type { DummyRuleMap } from 'oxlint';

export const reactRules = {
  'react/button-has-type': 'error',
  'react/capitalized-calls': 'error',
  'react/checked-requires-onchange-or-readonly': 'error',
  'react/display-name': 'error',
  'react/error-boundaries': 'error',
  'react/exhaustive-deps': 'error',
  'react/exhaustive-effect-dependencies': 'error',
  'react/forbid-component-props': 'off',
  'react/forbid-dom-props': 'off',
  'react/forbid-elements': 'off',
  'react/forward-ref-uses-ref': 'error',
  'react/function-component-definition': 'off',
  'react/globals': 'error',
  'react/hook-use-state': 'error',
  'react/hooks': 'error',
  'react/iframe-missing-sandbox': 'error',
  'react/immutability': 'error',
  'react/incompatible-library': 'error',
  'react/invariant': 'warn',
  'react/jsx-boolean-value': 'error',
  'react/jsx-curly-brace-presence': [
    'error',
    {
      props: 'never',
      children: 'never',
      propElementValues: 'always',
    },
  ],
  'react/jsx-filename-extension': 'off',
  'react/jsx-fragments': 'error',
  'react/jsx-handler-names': 'error',
  'react/jsx-key': 'error',
  'react/jsx-max-depth': 'off',
  'react/jsx-no-comment-textnodes': 'error',
  'react/jsx-no-constructed-context-values': 'error',
  'react/jsx-no-duplicate-props': 'error',
  'react/jsx-no-literals': 'error',
  'react/jsx-no-script-url': 'error',
  'react/jsx-no-target-blank': 'off',
  'react/jsx-no-undef': 'error',
  'react/jsx-no-useless-fragment': 'error',
  'react/jsx-pascal-case': 'off',
  'react/jsx-props-no-spread-multi': 'error',
  'react/jsx-props-no-spreading': 'off',
  'react/memo-dependencies': 'error',
  'react/no-array-index-key': 'error',
  'react/no-children-prop': 'error',
  'react/no-clone-element': 'error',
  'react/no-danger-with-children': 'error',
  'react/no-danger': 'error',
  'react/no-deriving-state-in-effects': 'error',
  'react/no-did-mount-set-state': 'off',
  'react/no-did-update-set-state': 'off',
  'react/no-direct-mutation-state': 'error',
  'react/no-find-dom-node': 'error',
  'react/no-is-mounted': 'error',
  'react/no-multi-comp': 'off',
  'react/no-namespace': 'error',
  'react/no-object-type-as-default-prop': 'error',
  'react/no-react-children': 'error',
  'react/no-redundant-should-component-update': 'off',
  'react/no-render-return-value': 'error',
  'react/no-set-state': 'off',
  'react/no-string-refs': 'error',
  'react/no-this-in-sfc': 'error',
  'react/no-unescaped-entities': 'error',
  'react/no-unknown-property': 'error',
  'react/no-unsafe': ['error', { checkAliases: true }],
  'react/no-unstable-nested-components': 'error',
  'react/no-will-update-set-state': 'off',
  'react/only-export-components': ['error', { allowConstantExport: true }],
  'react/prefer-es6-class': 'error',
  'react/prefer-function-component': 'error',
  'react/preserve-manual-memoization': 'error',
  'react/purity': 'error',
  'react/react-in-jsx-scope': 'off',
  'react/refs': 'error',
  'react/require-render-return': 'error',
  'react/rule-suppression': 'error',
  'react/rules-of-hooks': 'error',
  'react/self-closing-comp': 'error',
  'react/set-state-in-effect': 'error',
  'react/set-state-in-render': 'error',
  'react/state-in-constructor': 'off',
  'react/static-components': 'error',
  'react/style-prop-object': 'error',
  'react/syntax': 'error',
  'react/todo': 'warn',
  'react/unsupported-syntax': 'error',
  'react/use-memo': 'error',
  'react/void-dom-elements-no-children': 'error',
  'react/void-use-memo': 'error',
} as const satisfies DummyRuleMap;
