import type { DummyRuleMap } from 'oxlint';

export const typescriptRules = {
  'typescript/adjacent-overload-signatures': 'error',
  'typescript/array-type': ['error', { default: 'array-simple' }],
  'typescript/await-thenable': 'error',
  'typescript/ban-ts-comment': 'error',
  'typescript/ban-tslint-comment': 'error',
  'typescript/ban-types': 'off',
  'typescript/class-literal-property-style': 'error',
  'typescript/consistent-generic-constructors': 'error',
  'typescript/consistent-indexed-object-style': 'error',
  'typescript/consistent-return': 'off',
  'typescript/consistent-type-assertions': [
    'error',
    {
      arrayLiteralTypeAssertions: 'never',
      objectLiteralTypeAssertions: 'never',
    },
  ],
  'typescript/consistent-type-definitions': ['error', 'type'],
  'typescript/consistent-type-exports': 'error',
  'typescript/consistent-type-imports': 'off',
  'typescript/dot-notation': 'error',
  'typescript/explicit-function-return-type': 'off',
  'typescript/explicit-member-accessibility': [
    'error',
    {
      accessibility: 'explicit',
      overrides: { constructors: 'no-public' },
    },
  ],
  'typescript/explicit-module-boundary-types': 'error',
  'typescript/method-signature-style': 'error',
  'typescript/no-array-delete': 'error',
  'typescript/no-base-to-string': 'error',
  'typescript/no-confusing-non-null-assertion': 'error',
  'typescript/no-confusing-void-expression': 'error',
  'typescript/no-deprecated': 'warn',
  'typescript/no-duplicate-enum-values': 'off',
  'typescript/no-duplicate-type-constituents': 'error',
  'typescript/no-dynamic-delete': 'error',
  'typescript/no-empty-interface': 'off',
  'typescript/no-empty-object-type': 'error',
  'typescript/no-explicit-any': 'error',
  'typescript/no-extra-non-null-assertion': 'error',
  'typescript/no-extraneous-class': 'error',
  'typescript/no-floating-promises': ['error', { ignoreVoid: false }],
  'typescript/no-for-in-array': 'error',
  'typescript/no-implied-eval': 'error',
  'typescript/no-import-type-side-effects': 'error',
  'typescript/no-inferrable-types': 'error',
  'typescript/no-invalid-void-type': 'error',
  'typescript/no-meaningless-void-operator': 'error',
  'typescript/no-misused-new': 'error',
  'typescript/no-misused-promises': 'error',
  'typescript/no-misused-spread': 'error',
  'typescript/no-mixed-enums': 'off',
  'typescript/no-namespace': 'error',
  'typescript/no-non-null-asserted-nullish-coalescing': 'error',
  'typescript/no-non-null-asserted-optional-chain': 'error',
  'typescript/no-non-null-assertion': 'error',
  'typescript/no-redundant-type-constituents': 'error',
  'typescript/no-require-imports': 'error',
  'typescript/no-restricted-types': [
    'error',
    {
      types: {
        object: {
          message:
            'The `object` type is hard to use. Use `Record<string, unknown>` instead. See: https://github.com/typescript-eslint/typescript-eslint/pull/848',
          fixWith: 'Record<string, unknown>',
        },
        Buffer: {
          message:
            'Use Uint8Array instead. See: https://sindresorhus.com/blog/goodbye-nodejs-buffer',
          suggest: ['Uint8Array'],
        },
      },
    },
  ],
  'typescript/no-this-alias': 'error',
  'typescript/no-unnecessary-boolean-literal-compare': 'error',
  'typescript/no-unnecessary-condition': 'error',
  'typescript/no-unnecessary-parameter-property-assignment': 'off',
  'typescript/no-unnecessary-qualifier': 'off',
  'typescript/no-unnecessary-template-expression': 'error',
  'typescript/no-unnecessary-type-arguments': 'error',
  'typescript/no-unnecessary-type-assertion': 'error',
  'typescript/no-unnecessary-type-constraint': 'error',
  'typescript/no-unnecessary-type-conversion': 'error',
  'typescript/no-unnecessary-type-parameters': 'error',
  'typescript/no-unsafe-argument': 'error',
  'typescript/no-unsafe-assignment': 'error',
  'typescript/no-unsafe-call': 'error',
  'typescript/no-unsafe-declaration-merging': 'error',
  'typescript/no-unsafe-enum-comparison': 'error',
  'typescript/no-unsafe-function-type': 'error',
  'typescript/no-unsafe-member-access': 'error',
  'typescript/no-unsafe-return': 'error',
  'typescript/no-unsafe-type-assertion': 'error',
  'typescript/no-unsafe-unary-minus': 'error',
  'typescript/no-useless-default-assignment': 'error',
  'typescript/no-useless-empty-export': 'off',
  'typescript/no-var-requires': 'off',
  'typescript/no-wrapper-object-types': 'error',
  'typescript/non-nullable-type-assertion-style': 'off',
  'typescript/only-throw-error': 'error',
  'typescript/parameter-properties': 'off',
  'typescript/prefer-as-const': 'error',
  'typescript/prefer-enum-initializers': 'off',
  'typescript/prefer-find': 'error',
  'typescript/prefer-for-of': 'error',
  'typescript/prefer-function-type': 'error',
  'typescript/prefer-includes': 'error',
  'typescript/prefer-literal-enum-member': 'off',
  'typescript/prefer-namespace-keyword': 'off',
  'typescript/prefer-nullish-coalescing': 'error',
  'typescript/prefer-optional-chain': 'error',
  'typescript/prefer-promise-reject-errors': 'error',
  'typescript/prefer-readonly': 'error',
  'typescript/prefer-readonly-parameter-types': 'off',
  'typescript/prefer-reduce-type-parameter': 'error',
  'typescript/prefer-regexp-exec': 'error',
  'typescript/prefer-return-this-type': 'error',
  'typescript/prefer-string-starts-ends-with': 'error',
  'typescript/prefer-ts-expect-error': 'off',
  'typescript/promise-function-async': 'off',
  'typescript/related-getter-setter-pairs': 'error',
  'typescript/require-array-sort-compare': 'error',
  'typescript/require-await': 'error',
  'typescript/restrict-plus-operands': [
    'error',
    {
      allowAny: false,
      allowBoolean: false,
      allowNullish: false,
      allowNumberAndString: false,
      allowRegExp: false,
    },
  ],
  'typescript/restrict-template-expressions': [
    'error',
    {
      allowAny: false,
      allowBoolean: false,
      allowNever: false,
      allowNullish: false,
      allowNumber: false,
      allowRegExp: false,
    },
  ],
  'typescript/return-await': ['error', 'in-try-catch'],
  'typescript/strict-boolean-expressions': 'error',
  'typescript/strict-void-return': 'off',
  'typescript/switch-exhaustiveness-check': [
    'error',
    {
      allowDefaultCaseForExhaustiveSwitch: false,
      requireDefaultForNonUnion: true,
    },
  ],
  'typescript/triple-slash-reference': [
    'error',
    {
      path: 'never',
      types: 'never',
      lib: 'never',
    },
  ],
  'typescript/unbound-method': 'error',
  'typescript/unified-signatures': 'error',
  'typescript/use-unknown-in-catch-callback-variable': 'error',
} as const satisfies DummyRuleMap;
