import * as eslintComments from '@eslint-community/eslint-plugin-eslint-comments';
import type { ESLint, Linter } from 'eslint';
import * as depend from 'eslint-plugin-depend';
import { importX } from 'eslint-plugin-import-x';
import unicorn from 'eslint-plugin-unicorn';

export const base = {
  name: 'priver/base',
  languageOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  linterOptions: {
    reportUnusedDisableDirectives: 'error',
    reportUnusedInlineConfigs: 'error',
  },
  plugins: {
    '@eslint-community/eslint-comments': eslintComments,
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion -- TS2883
    'import-x': importX as ESLint.Plugin,
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion -- TS2883
    'unicorn': unicorn as ESLint.Plugin,
    'depend': depend,
  },
  rules: {
    // Core: possible problems
    'array-callback-return': ['error', { allowImplicit: true }],
    'constructor-super': 'error',
    'for-direction': 'error',
    'getter-return': 'error',
    'no-async-promise-executor': 'error',
    'no-await-in-loop': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': ['error', 'always'],
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-constructor-return': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-duplicate-imports': 'off',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-ex-assign': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-import-assign': 'error',
    'no-inner-declarations': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-obj-calls': 'error',
    'no-promise-executor-return': 'error',
    'no-prototype-builtins': 'error',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    'no-setter-return': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-this-before-super': 'error',
    'no-unassigned-vars': 'error',
    'no-undef': 'error',
    'no-unexpected-multiline': 'off',
    'no-unmodified-loop-condition': 'error',
    'no-unreachable-loop': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': ['error', { enforceForOrderingRelations: true }],
    'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
    'no-unused-private-class-members': 'error',
    'no-unused-vars': ['error', { ignoreRestSiblings: true }],
    'no-use-before-define': 'off',
    'no-useless-assignment': 'error',
    'no-useless-backreference': 'error',
    'require-atomic-updates': ['error', { allowProperties: true }],
    'use-isnan': 'error',
    'valid-typeof': 'error',

    // Core: suggestions
    'accessor-pairs': 'error',
    'arrow-body-style': 'error',
    'block-scoped-var': 'error',
    'camelcase': ['error', { properties: 'never' }],
    'capitalized-comments': 'off',
    'class-methods-use-this': 'off',
    'complexity': 'off',
    'consistent-return': 'error',
    'consistent-this': 'off',
    'curly': 'error',
    'default-case-last': 'error',
    'default-case': 'error',
    'default-param-last': 'error',
    'dot-notation': 'error',
    'eqeqeq': 'error',
    'func-name-matching': 'off',
    'func-names': 'off',
    'func-style': ['error', 'declaration'],
    'grouped-accessor-pairs': ['error', 'getBeforeSet'],
    'guard-for-in': 'error',
    'id-denylist': 'off',
    'id-length': 'off',
    'id-match': 'off',
    'init-declarations': 'off',
    'logical-assignment-operators': 'off', // unicorn/logical-assignment-operators
    'max-classes-per-file': 'off',
    'max-depth': 'off',
    'max-lines-per-function': 'off',
    'max-lines': 'off',
    'max-nested-callbacks': 'off',
    'max-params': 'off',
    'max-statements': 'off',
    'new-cap': 'error',
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-bitwise': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-console': 'error',
    'no-continue': 'error',
    'no-delete-var': 'error',
    'no-div-regex': 'error',
    'no-else-return': ['error', { allowElseIf: false }],
    'no-empty-function': 'off',
    'no-empty-static-block': 'error',
    'no-empty': ['error', { allowEmptyCatch: true }],
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-boolean-cast': ['error', { enforceForInnerExpressions: true }],
    'no-extra-label': 'error',
    'no-global-assign': 'error',
    'no-implicit-coercion': 'error',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-inline-comments': 'off',
    'no-invalid-this': 'off',
    'no-iterator': 'error',
    'no-label-var': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'error',
    'no-magic-numbers': 'off',
    'no-multi-assign': 'error',
    'no-multi-str': 'error',
    'no-negated-condition': 'off',
    'no-nested-ternary': 'off',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-new': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-object-constructor': 'error',
    'no-octal-escape': 'error',
    'no-octal': 'error',
    'no-param-reassign': 'error',
    'no-plusplus': 'off',
    'no-proto': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-restricted-exports': 'off',
    'no-restricted-globals': [
      'error',
      {
        name: 'Buffer',
        message: 'Use Uint8Array instead. See: https://sindresorhus.com/blog/goodbye-nodejs-buffer',
      },
      {
        name: 'atob',
        message:
          'This API is deprecated. Use https://github.com/sindresorhus/uint8array-extras instead.',
      },
      {
        name: 'btoa',
        message:
          'This API is deprecated. Use https://github.com/sindresorhus/uint8array-extras instead.',
      },
    ],
    'no-restricted-imports': 'off',
    'no-restricted-properties': 'off',
    'no-restricted-syntax': 'off',
    'no-return-assign': ['error', 'always'],
    'no-script-url': 'error',
    'no-sequences': 'error',
    'no-shadow-restricted-names': 'error',
    'no-shadow': 'error',
    'no-ternary': 'off',
    'no-throw-literal': 'error',
    'no-undef-init': 'error',
    'no-undefined': 'off',
    'no-underscore-dangle': 'off',
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': ['error', { enforceForJSX: true }],
    'no-unused-labels': 'error',
    'no-useless-call': 'error',
    'no-useless-catch': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'off', // unicorn/no-useless-concat
    'no-useless-constructor': 'error',
    'no-useless-escape': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'no-warning-comments': 'off',
    'no-with': 'error',
    'object-shorthand': [
      'error',
      'always',
      {
        avoidExplicitReturnArrows: true,
        avoidQuotes: true,
      },
    ],
    'one-var': ['error', 'never'],
    'operator-assignment': 'off', // unicorn/operator-assignment
    'prefer-arrow-callback': ['error', { allowNamedFunctions: true }],
    'prefer-const': ['error', { destructuring: 'all' }],
    'prefer-destructuring': [
      'error',
      {
        VariableDeclarator: {
          array: false,
          object: true,
        },
        AssignmentExpression: {
          array: false,
          object: false,
        },
      },
      { enforceForRenamedProperties: false },
    ],
    'prefer-exponentiation-operator': 'error',
    'prefer-named-capture-group': 'off',
    'prefer-numeric-literals': 'error',
    'prefer-object-has-own': 'error',
    'prefer-object-spread': 'error',
    'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
    'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'off',
    'preserve-caught-error': 'error',
    'radix': 'error',
    'require-await': 'off',
    'require-unicode-regexp': 'error',
    'require-yield': 'error',
    'sort-imports': 'off',
    'sort-keys': 'off',
    'sort-vars': 'off',
    'strict': ['error', 'global'],
    'symbol-description': 'error',
    'vars-on-top': 'off',
    'yoda': 'error',

    // Core: layout and formatting
    'unicode-bom': 'error',

    // ESLint comments
    '@eslint-community/eslint-comments/disable-enable-pair': 'error',
    '@eslint-community/eslint-comments/no-aggregating-enable': 'error',
    '@eslint-community/eslint-comments/no-duplicate-disable': 'error',
    '@eslint-community/eslint-comments/no-unlimited-disable': 'error',
    '@eslint-community/eslint-comments/no-unused-enable': 'error',
    '@eslint-community/eslint-comments/no-restricted-disable': 'off',
    '@eslint-community/eslint-comments/no-use': 'off',
    '@eslint-community/eslint-comments/require-description': [
      'error',
      { ignore: ['eslint-enable'] },
    ],

    // Import: helpful warnings
    'import-x/export': 'error',
    'import-x/no-deprecated': 'warn',
    'import-x/no-empty-named-blocks': 'error',
    'import-x/no-extraneous-dependencies': [
      'error',
      {
        includeTypes: true,
        peerDependencies: false,
      },
    ],
    'import-x/no-mutable-exports': 'error',
    'import-x/no-named-as-default-member': 'error',
    'import-x/no-named-as-default': 'error',
    'import-x/no-rename-default': 'off',
    'import-x/no-useless-path-segments': 'error',

    // Import: module systems
    'import-x/no-amd': 'error',
    'import-x/no-commonjs': 'off',
    'import-x/no-import-module-exports': 'error',
    'import-x/no-nodejs-modules': 'off',
    'import-x/unambiguous': 'off',

    // Import: static analysis
    'import-x/default': 'error',
    'import-x/named': 'error',
    'import-x/namespace': 'error',
    'import-x/no-absolute-path': 'error',
    'import-x/no-cycle': 'error',
    'import-x/no-dynamic-require': 'error',
    'import-x/no-internal-modules': 'off',
    'import-x/no-relative-packages': 'off',
    'import-x/no-relative-parent-imports': 'off',
    'import-x/no-restricted-paths': 'off',
    'import-x/no-self-import': 'error',
    'import-x/no-unresolved': 'error',
    'import-x/no-unused-modules': 'off',
    'import-x/no-webpack-loader-syntax': 'error',

    // Import: style guide
    'import-x/consistent-type-specifier-style': 'off',
    'import-x/dynamic-import-chunkname': 'off',
    'import-x/exports-last': 'off',
    'import-x/extensions': ['error', 'ignorePackages'],
    'import-x/first': 'error',
    'import-x/group-exports': 'off',
    'import-x/max-dependencies': 'off',
    'import-x/newline-after-import': 'off',
    'import-x/no-anonymous-default-export': 'off',
    'import-x/no-default-export': 'off',
    'import-x/no-duplicates': ['error', { 'prefer-inline': true }],
    'import-x/no-named-default': 'error',
    'import-x/no-named-export': 'off',
    'import-x/no-namespace': 'off',
    'import-x/no-unassigned-import': 'off',
    'import-x/order': 'off',
    'import-x/prefer-default-export': 'off',
    'import-x/prefer-namespace-import': 'off', // unicorn/import-style

    // Unicorn
    'unicorn/better-dom-traversing': 'error',
    'unicorn/catch-error-name': 'error',
    'unicorn/class-reference-in-static-methods': 'error',
    'unicorn/comment-content': 'error',
    'unicorn/consistent-arrow-return-style': 'off',
    'unicorn/consistent-assert': 'error',
    'unicorn/consistent-boolean-name': 'off',
    'unicorn/consistent-class-member-order': 'off',
    'unicorn/consistent-compound-words': 'error',
    'unicorn/consistent-conditional-object-spread': 'error',
    'unicorn/consistent-date-clone': 'error',
    'unicorn/consistent-destructuring': 'error',
    'unicorn/consistent-empty-array-spread': 'error',
    'unicorn/consistent-existence-index-check': 'error',
    'unicorn/consistent-export-decorator-position': 'off',
    'unicorn/consistent-function-scoping': 'error',
    'unicorn/consistent-function-style': 'off',
    'unicorn/consistent-json-file-read': 'error',
    'unicorn/consistent-optional-chaining': 'error',
    'unicorn/consistent-template-literal-escape': 'error',
    'unicorn/consistent-tuple-labels': 'error',
    'unicorn/custom-error-definition': 'error',
    'unicorn/default-export-style': 'error',
    'unicorn/dom-node-dataset': 'error',
    'unicorn/empty-brace-spaces': 'off',
    'unicorn/error-message': 'error',
    'unicorn/escape-case': 'error',
    'unicorn/expiring-todo-comments': ['warn', { allowWarningComments: false }],
    'unicorn/explicit-length-check': 'error',
    'unicorn/explicit-timer-delay': 'error',
    'unicorn/filename-case': 'error',
    'unicorn/id-match': 'off',
    'unicorn/import-style': [
      'error',
      {
        styles: {
          'react': { namespace: true },
          'react-dom': { namespace: true },
        },
      },
    ],
    'unicorn/isolated-functions': 'error',
    'unicorn/iteration-fallback-style': 'off',
    'unicorn/logical-assignment-operators': ['error', 'always', { enforceForIfStatements: true }],
    'unicorn/max-nested-calls': 'off',
    'unicorn/name-replacements': 'off',
    'unicorn/new-for-builtins': 'error',
    'unicorn/no-abusive-eslint-disable': 'off',
    'unicorn/no-accessor-recursion': 'error',
    'unicorn/no-accidental-bitwise-operator': 'off',
    'unicorn/no-anonymous-default-export': 'error',
    'unicorn/no-array-callback-reference': 'error',
    'unicorn/no-array-concat-in-loop': 'error',
    'unicorn/no-array-fill-with-reference-type': 'error',
    'unicorn/no-array-from-fill': 'error',
    'unicorn/no-array-front-mutation': 'off',
    'unicorn/no-array-method-this-argument': 'error',
    'unicorn/no-array-reduce': 'error',
    'unicorn/no-array-reverse': 'error',
    'unicorn/no-array-sort': 'error',
    'unicorn/no-array-sort-for-min-max': 'error',
    'unicorn/no-array-splice': 'error',
    'unicorn/no-asterisk-prefix-in-documentation-comments': 'off',
    'unicorn/no-async-promise-finally': 'error',
    'unicorn/no-await-expression-member': 'error',
    'unicorn/no-await-in-promise-methods': 'error',
    'unicorn/no-barrel-files': 'error',
    'unicorn/no-blob-to-file': 'error',
    'unicorn/no-boolean-sort-comparator': 'error',
    'unicorn/no-break-in-nested-loop': 'error',
    'unicorn/no-canvas-to-image': 'error',
    'unicorn/no-chained-comparison': 'error',
    'unicorn/no-collection-bracket-access': 'error',
    'unicorn/no-computed-property-existence-check': 'error',
    'unicorn/no-confusing-array-splice': 'error',
    'unicorn/no-confusing-array-with': 'error',
    'unicorn/no-console-spaces': 'error',
    'unicorn/no-constant-zero-expression': 'error',
    'unicorn/no-declarations-before-early-exit': 'error',
    'unicorn/no-document-cookie': 'error',
    'unicorn/no-double-comparison': 'error',
    'unicorn/no-duplicate-if-branches': 'error',
    'unicorn/no-duplicate-logical-operands': 'error',
    'unicorn/no-duplicate-loops': 'error',
    'unicorn/no-duplicate-set-values': 'error',
    'unicorn/no-empty-file': 'error',
    'unicorn/no-error-property-assignment': 'error',
    'unicorn/no-exports-in-scripts': 'error',
    'unicorn/no-for-each': 'error',
    'unicorn/no-for-loop': 'error',
    'unicorn/no-global-object-property-assignment': 'error',
    'unicorn/no-immediate-mutation': 'error',
    'unicorn/no-impossible-length-comparison': 'error',
    'unicorn/no-incorrect-query-selector': 'error',
    'unicorn/no-incorrect-template-string-interpolation': 'error',
    'unicorn/no-instanceof-builtins': 'error',
    'unicorn/no-invalid-argument-count': 'error',
    'unicorn/no-invalid-character-comparison': 'error',
    'unicorn/no-invalid-fetch-options': 'error',
    'unicorn/no-invalid-file-input-accept': 'off',
    'unicorn/no-invalid-remove-event-listener': 'error',
    'unicorn/no-invalid-well-known-symbol-methods': 'error',
    'unicorn/no-keyword-prefix': 'off',
    'unicorn/no-late-current-target-access': 'error',
    'unicorn/no-late-event-control': 'error',
    'unicorn/no-lonely-if': 'error',
    'unicorn/no-loop-iterable-mutation': 'error',
    'unicorn/no-magic-array-flat-depth': 'error',
    'unicorn/no-manually-wrapped-comments': 'off',
    'unicorn/no-mismatched-map-key': 'error',
    'unicorn/no-misrefactored-assignment': 'error',
    'unicorn/no-missing-local-resource': 'off',
    'unicorn/no-multiple-promise-resolver-calls': 'error',
    'unicorn/no-named-default': 'off', // import-x/no-named-default
    'unicorn/no-negated-array-predicate': 'error',
    'unicorn/no-negated-comparison': 'error',
    'unicorn/no-negated-condition': 'error',
    'unicorn/no-negation-in-equality-check': 'error',
    'unicorn/no-nested-ternary': 'off',
    'unicorn/no-new-array': 'error',
    'unicorn/no-new-buffer': 'error',
    'unicorn/no-non-function-verb-prefix': 'off',
    'unicorn/no-nonstandard-builtin-properties': 'error',
    'unicorn/no-null': 'off',
    'unicorn/no-object-as-default-parameter': 'error',
    'unicorn/no-object-methods-with-collections': 'error',
    'unicorn/no-optional-chaining-on-undeclared-variable': 'error',
    'unicorn/no-process-exit': 'error',
    'unicorn/no-redundant-comparison': 'error',
    'unicorn/no-return-array-push': 'error',
    'unicorn/no-selector-as-dom-name': 'error',
    'unicorn/no-shorthand-property-overrides': 'off',
    'unicorn/no-single-promise-in-promise-methods': 'error',
    'unicorn/no-static-only-class': 'error',
    'unicorn/no-subtraction-comparison': 'error',
    'unicorn/no-thenable': 'error',
    'unicorn/no-this-assignment': 'error',
    'unicorn/no-this-outside-of-class': 'error',
    'unicorn/no-top-level-assignment-in-function': 'error',
    'unicorn/no-top-level-side-effects': 'error',
    'unicorn/no-transition-all': 'off',
    'unicorn/no-typeof-undefined': 'error',
    'unicorn/no-uncalled-method': 'error',
    'unicorn/no-undeclared-class-members': 'error',
    'unicorn/no-unnecessary-await': 'error',
    'unicorn/no-unnecessary-array-flat-depth': 'error',
    'unicorn/no-unnecessary-array-flat-map': 'error',
    'unicorn/no-unnecessary-array-splice-count': 'error',
    'unicorn/no-unnecessary-boolean-comparison': 'error',
    'unicorn/no-unnecessary-fetch-options': 'error',
    'unicorn/no-unnecessary-global-this': 'error',
    'unicorn/no-unnecessary-nested-ternary': 'error',
    'unicorn/no-unnecessary-polyfills': 'error',
    'unicorn/no-unnecessary-slice-end': 'error',
    'unicorn/no-unnecessary-splice': 'error',
    'unicorn/no-unnecessary-string-trim': 'error',
    'unicorn/no-unreadable-array-destructuring': 'error',
    'unicorn/no-unreadable-for-of-expression': 'error',
    'unicorn/no-unreadable-iife': 'error',
    'unicorn/no-unreadable-new-expression': 'off',
    'unicorn/no-unreadable-object-destructuring': 'error',
    'unicorn/no-unsafe-buffer-conversion': 'error',
    'unicorn/no-unsafe-dom-html': 'off',
    'unicorn/no-unsafe-promise-all-settled-values': 'error',
    'unicorn/no-unsafe-property-key': 'error',
    'unicorn/no-unsafe-sqlite-interpolation': 'error',
    'unicorn/no-unsafe-string-replacement': 'error',
    'unicorn/no-unused-array-method-return': 'error',
    'unicorn/no-unused-properties': 'off',
    'unicorn/no-useless-boolean-cast': 'error',
    'unicorn/no-useless-coercion': 'error',
    'unicorn/no-useless-collection-argument': 'error',
    'unicorn/no-useless-compound-assignment': 'error',
    'unicorn/no-useless-concat': 'error',
    'unicorn/no-useless-continue': 'error',
    'unicorn/no-useless-delete-check': 'error',
    'unicorn/no-useless-else': 'error',
    'unicorn/no-useless-error-capture-stack-trace': 'error',
    'unicorn/no-useless-fallback-in-spread': 'error',
    'unicorn/no-useless-iterator-to-array': 'error',
    'unicorn/no-useless-length-check': 'error',
    'unicorn/no-useless-logical-operand': 'error',
    'unicorn/no-useless-override': 'error',
    'unicorn/no-useless-promise-resolve-reject': 'error',
    'unicorn/no-useless-re-export': 'error',
    'unicorn/no-useless-recursion': 'error',
    'unicorn/no-useless-spread': 'error',
    'unicorn/no-useless-switch-case': 'error',
    'unicorn/no-useless-template-literals': 'error',
    'unicorn/no-useless-undefined': 'error',
    'unicorn/no-xor-as-exponentiation': 'error',
    'unicorn/no-zero-fractions': 'error',
    'unicorn/number-literal-case': 'off',
    'unicorn/numeric-separators-style': 'error',
    'unicorn/operator-assignment': ['error', 'always'],
    'unicorn/prefer-abort-signal-any': 'error',
    'unicorn/prefer-abort-signal-timeout': 'error',
    'unicorn/prefer-add-event-listener': 'error',
    'unicorn/prefer-add-event-listener-options': 'error',
    'unicorn/prefer-aggregate-error': 'error',
    'unicorn/prefer-array-find': 'error',
    'unicorn/prefer-array-flat-map': 'error',
    'unicorn/prefer-array-flat': 'error',
    'unicorn/prefer-array-from-async': 'error',
    'unicorn/prefer-array-from-map': 'error',
    'unicorn/prefer-array-from-range': 'error',
    'unicorn/prefer-array-index-of': 'error',
    'unicorn/prefer-array-iterable-methods': 'error',
    'unicorn/prefer-array-last-methods': 'error',
    'unicorn/prefer-array-slice': 'error',
    'unicorn/prefer-array-some': 'error',
    'unicorn/prefer-at': 'error',
    'unicorn/prefer-await': 'error',
    'unicorn/prefer-bigint-literals': 'error',
    'unicorn/prefer-blob-reading-methods': 'error',
    'unicorn/prefer-block-statement-over-iife': 'error',
    'unicorn/prefer-boolean-return': 'error',
    'unicorn/prefer-class-fields': 'error',
    'unicorn/prefer-classlist-toggle': 'error',
    'unicorn/prefer-code-point': 'error',
    'unicorn/prefer-continue': 'off',
    'unicorn/prefer-date-now': 'error',
    'unicorn/prefer-default-parameters': 'error',
    'unicorn/prefer-direct-iteration': 'error',
    'unicorn/prefer-dispose': 'error',
    'unicorn/prefer-dom-node-append': 'error',
    'unicorn/prefer-dom-node-html-methods': 'error',
    'unicorn/prefer-dom-node-remove': 'error',
    'unicorn/prefer-dom-node-replace-children': 'error',
    'unicorn/prefer-dom-node-text-content': 'error',
    'unicorn/prefer-early-return': 'error',
    'unicorn/prefer-else-if': 'error',
    'unicorn/prefer-error-is-error': 'off',
    'unicorn/prefer-event-target': 'error',
    'unicorn/prefer-explicit-viewport-units': 'off',
    'unicorn/prefer-export-from': 'error',
    'unicorn/prefer-flat-math-min-max': 'error',
    'unicorn/prefer-get-or-insert-computed': 'error',
    'unicorn/prefer-global-number-constants': 'error',
    'unicorn/prefer-global-this': 'error',
    'unicorn/prefer-group-by': 'error',
    'unicorn/prefer-has-check': 'error',
    'unicorn/prefer-hoisting-branch-code': 'error',
    'unicorn/prefer-https': 'error',
    'unicorn/prefer-identifier-import-export-specifiers': 'error',
    'unicorn/prefer-import-meta-properties': 'error',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-includes-over-repeated-comparisons': 'off',
    'unicorn/prefer-iterable-in-constructor': 'error',
    'unicorn/prefer-iterator-concat': 'off',
    'unicorn/prefer-iterator-helpers': 'error',
    'unicorn/prefer-iterator-to-array': 'error',
    'unicorn/prefer-iterator-to-array-at-end': 'error',
    'unicorn/prefer-keyboard-event-key': 'error',
    'unicorn/prefer-location-assign': 'error',
    'unicorn/prefer-logical-operator-over-ternary': 'error',
    'unicorn/prefer-map-from-entries': 'error',
    'unicorn/prefer-math-abs': 'error',
    'unicorn/prefer-math-constants': 'error',
    'unicorn/prefer-math-min-max': 'error',
    'unicorn/prefer-math-trunc': 'error',
    'unicorn/prefer-minimal-ternary': 'error',
    'unicorn/prefer-modern-dom-apis': 'error',
    'unicorn/prefer-modern-math-apis': 'error',
    'unicorn/prefer-module': 'error',
    'unicorn/prefer-native-coercion-functions': 'error',
    'unicorn/prefer-negative-index': 'error',
    'unicorn/prefer-node-protocol': 'off', // n/prefer-node-protocol
    'unicorn/prefer-number-coercion': 'error',
    'unicorn/prefer-number-is-safe-integer': 'error',
    'unicorn/prefer-number-properties': 'error',
    'unicorn/prefer-object-define-properties': 'error',
    'unicorn/prefer-object-destructuring-defaults': 'error',
    'unicorn/prefer-object-from-entries': 'error',
    'unicorn/prefer-object-iterable-methods': 'error',
    'unicorn/prefer-observer-apis': 'error',
    'unicorn/prefer-optional-catch-binding': 'error',
    'unicorn/prefer-path2d': 'error',
    'unicorn/prefer-private-class-fields': 'error',
    'unicorn/prefer-promise-try': 'error',
    'unicorn/prefer-promise-with-resolvers': 'error',
    'unicorn/prefer-prototype-methods': 'error',
    'unicorn/prefer-query-selector': 'error',
    'unicorn/prefer-queue-microtask': 'error',
    'unicorn/prefer-reflect-apply': 'error',
    'unicorn/prefer-regexp-escape': 'off',
    'unicorn/prefer-regexp-test': 'error',
    'unicorn/prefer-response-static-json': 'error',
    'unicorn/prefer-scoped-selector': 'error',
    'unicorn/prefer-set-has': 'error',
    'unicorn/prefer-set-methods': 'error',
    'unicorn/prefer-set-size': 'error',
    'unicorn/prefer-short-arrow-method': 'off',
    'unicorn/prefer-simple-condition-first': 'error',
    'unicorn/prefer-simple-sort-comparator': 'error',
    'unicorn/prefer-simplified-conditions': 'error',
    'unicorn/prefer-single-array-predicate': 'error',
    'unicorn/prefer-single-call': 'error',
    'unicorn/prefer-single-object-destructuring': 'error',
    'unicorn/prefer-single-replace': 'error',
    'unicorn/prefer-smaller-scope': 'error',
    'unicorn/prefer-split-limit': 'error',
    'unicorn/prefer-spread': 'error',
    'unicorn/prefer-string-match-all': 'error',
    'unicorn/prefer-string-pad-start-end': 'error',
    'unicorn/prefer-string-raw': 'error',
    'unicorn/prefer-string-repeat': 'error',
    'unicorn/prefer-string-replace-all': 'error',
    'unicorn/prefer-string-slice': 'error',
    'unicorn/prefer-string-starts-ends-with': 'error',
    'unicorn/prefer-string-trim-start-end': 'error',
    'unicorn/prefer-structured-clone': 'error',
    'unicorn/prefer-switch': 'error',
    'unicorn/prefer-temporal': 'off',
    'unicorn/prefer-ternary': 'error',
    'unicorn/prefer-then-catch': 'error',
    'unicorn/prefer-toggle-attribute': 'error',
    'unicorn/prefer-top-level-await': 'error',
    'unicorn/prefer-type-error': 'error',
    'unicorn/prefer-type-literal-last': 'error',
    'unicorn/prefer-uint8array-base64': 'off',
    'unicorn/prefer-unary-minus': 'error',
    'unicorn/prefer-unicode-code-point-escapes': 'error',
    'unicorn/prefer-url-can-parse': 'error',
    'unicorn/prefer-url-href': 'error',
    'unicorn/prefer-url-search-parameters': 'error',
    'unicorn/prefer-while-loop-condition': 'error',
    'unicorn/relative-url-style': 'error',
    'unicorn/require-array-join-separator': 'error',
    'unicorn/require-array-sort-compare': 'error',
    'unicorn/require-css-escape': 'error',
    'unicorn/require-frontmatter-fields': 'off',
    'unicorn/require-module-attributes': 'error',
    'unicorn/require-module-specifiers': 'error',
    'unicorn/require-number-to-fixed-digits-argument': 'error',
    'unicorn/require-passive-events': 'error',
    'unicorn/require-post-message-target-origin': 'off',
    'unicorn/require-proxy-trap-boolean-return': 'error',
    'unicorn/single-line-block-comment-style': 'off',
    'unicorn/string-content': 'off',
    'unicorn/switch-case-break-position': 'error',
    'unicorn/switch-case-braces': ['error', 'avoid'],
    'unicorn/template-indent': 'off',
    'unicorn/text-encoding-identifier-case': 'error',
    'unicorn/throw-new-error': 'error',
    'unicorn/try-complexity': 'off',

    // Depend
    'depend/ban-dependencies': 'error',
  },
} as const satisfies Linter.Config;
